/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as OnboardingSourcesRouteImport } from './routes/onboarding/sources'
import { Route as OnboardingFinishRouteImport } from './routes/onboarding/finish'
import { Route as OnboardingAudienceRouteImport } from './routes/onboarding/audience'
import { Route as OnboardingAboutRouteImport } from './routes/onboarding/about'
import { Route as AppSupportRouteImport } from './routes/app/support'
import { Route as AppSummariesRouteImport } from './routes/app/summaries'
import { Route as AppSourcesRouteImport } from './routes/app/sources'
import { Route as AppInboxRouteImport } from './routes/app/inbox'
import { Route as AppFeedbackRouteImport } from './routes/app/feedback'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppSettingsRouteRouteImport } from './routes/app/settings/route'
import { Route as AppWatchlistsIndexRouteImport } from './routes/app/watchlists/index'
import { Route as AppOutcomesIndexRouteImport } from './routes/app/outcomes/index'
import { Route as AppIcpsIndexRouteImport } from './routes/app/icps/index'
import { Route as AppDraftsIndexRouteImport } from './routes/app/drafts/index'
import { Route as AppWatchlistsWatchlistIdRouteImport } from './routes/app/watchlists/$watchlistId'
import { Route as AppSignalsSignalIdRouteImport } from './routes/app/signals/$signalId'
import { Route as AppSettingsWorkspaceRouteImport } from './routes/app/settings/workspace'
import { Route as AppSettingsSecurityRouteImport } from './routes/app/settings/security'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app/settings/notifications'
import { Route as AppSettingsMembersRouteImport } from './routes/app/settings/members'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/app/settings/integrations'
import { Route as AppOutcomesOutcomeIdRouteImport } from './routes/app/outcomes/$outcomeId'
import { Route as AppIcpsIcpIdRouteImport } from './routes/app/icps/$icpId'
import { Route as AppDraftsNewRouteImport } from './routes/app/drafts/new'
import { Route as AppDraftsDraftIdRouteImport } from './routes/app/drafts/$draftId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const OnboardingSourcesRoute = OnboardingSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingFinishRoute = OnboardingFinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingAudienceRoute = OnboardingAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingAboutRoute = OnboardingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSummariesRoute = AppSummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWatchlistsIndexRoute = AppWatchlistsIndexRouteImport.update({
  id: '/watchlists/',
  path: '/watchlists/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOutcomesIndexRoute = AppOutcomesIndexRouteImport.update({
  id: '/outcomes/',
  path: '/outcomes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIcpsIndexRoute = AppIcpsIndexRouteImport.update({
  id: '/icps/',
  path: '/icps/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDraftsIndexRoute = AppDraftsIndexRouteImport.update({
  id: '/drafts/',
  path: '/drafts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWatchlistsWatchlistIdRoute =
  AppWatchlistsWatchlistIdRouteImport.update({
    id: '/watchlists/$watchlistId',
    path: '/watchlists/$watchlistId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSignalsSignalIdRoute = AppSignalsSignalIdRouteImport.update({
  id: '/signals/$signalId',
  path: '/signals/$signalId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsWorkspaceRoute = AppSettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppOutcomesOutcomeIdRoute = AppOutcomesOutcomeIdRouteImport.update({
  id: '/outcomes/$outcomeId',
  path: '/outcomes/$outcomeId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIcpsIcpIdRoute = AppIcpsIcpIdRouteImport.update({
  id: '/icps/$icpId',
  path: '/icps/$icpId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDraftsNewRoute = AppDraftsNewRouteImport.update({
  id: '/drafts/new',
  path: '/drafts/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDraftsDraftIdRoute = AppDraftsDraftIdRouteImport.update({
  id: '/drafts/$draftId',
  path: '/drafts/$draftId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/sources': typeof AppSourcesRoute
  '/app/summaries': typeof AppSummariesRoute
  '/app/support': typeof AppSupportRoute
  '/onboarding/about': typeof OnboardingAboutRoute
  '/onboarding/audience': typeof OnboardingAudienceRoute
  '/onboarding/finish': typeof OnboardingFinishRoute
  '/onboarding/sources': typeof OnboardingSourcesRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/drafts/$draftId': typeof AppDraftsDraftIdRoute
  '/app/drafts/new': typeof AppDraftsNewRoute
  '/app/icps/$icpId': typeof AppIcpsIcpIdRoute
  '/app/outcomes/$outcomeId': typeof AppOutcomesOutcomeIdRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/app/signals/$signalId': typeof AppSignalsSignalIdRoute
  '/app/watchlists/$watchlistId': typeof AppWatchlistsWatchlistIdRoute
  '/app/drafts/': typeof AppDraftsIndexRoute
  '/app/icps/': typeof AppIcpsIndexRoute
  '/app/outcomes/': typeof AppOutcomesIndexRoute
  '/app/watchlists/': typeof AppWatchlistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/sources': typeof AppSourcesRoute
  '/app/summaries': typeof AppSummariesRoute
  '/app/support': typeof AppSupportRoute
  '/onboarding/about': typeof OnboardingAboutRoute
  '/onboarding/audience': typeof OnboardingAudienceRoute
  '/onboarding/finish': typeof OnboardingFinishRoute
  '/onboarding/sources': typeof OnboardingSourcesRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/drafts/$draftId': typeof AppDraftsDraftIdRoute
  '/app/drafts/new': typeof AppDraftsNewRoute
  '/app/icps/$icpId': typeof AppIcpsIcpIdRoute
  '/app/outcomes/$outcomeId': typeof AppOutcomesOutcomeIdRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/app/signals/$signalId': typeof AppSignalsSignalIdRoute
  '/app/watchlists/$watchlistId': typeof AppWatchlistsWatchlistIdRoute
  '/app/drafts': typeof AppDraftsIndexRoute
  '/app/icps': typeof AppIcpsIndexRoute
  '/app/outcomes': typeof AppOutcomesIndexRoute
  '/app/watchlists': typeof AppWatchlistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/sources': typeof AppSourcesRoute
  '/app/summaries': typeof AppSummariesRoute
  '/app/support': typeof AppSupportRoute
  '/onboarding/about': typeof OnboardingAboutRoute
  '/onboarding/audience': typeof OnboardingAudienceRoute
  '/onboarding/finish': typeof OnboardingFinishRoute
  '/onboarding/sources': typeof OnboardingSourcesRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/drafts/$draftId': typeof AppDraftsDraftIdRoute
  '/app/drafts/new': typeof AppDraftsNewRoute
  '/app/icps/$icpId': typeof AppIcpsIcpIdRoute
  '/app/outcomes/$outcomeId': typeof AppOutcomesOutcomeIdRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/app/signals/$signalId': typeof AppSignalsSignalIdRoute
  '/app/watchlists/$watchlistId': typeof AppWatchlistsWatchlistIdRoute
  '/app/drafts/': typeof AppDraftsIndexRoute
  '/app/icps/': typeof AppIcpsIndexRoute
  '/app/outcomes/': typeof AppOutcomesIndexRoute
  '/app/watchlists/': typeof AppWatchlistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/login'
    | '/mcp'
    | '/register'
    | '/app/settings'
    | '/app/analytics'
    | '/app/feedback'
    | '/app/inbox'
    | '/app/sources'
    | '/app/summaries'
    | '/app/support'
    | '/onboarding/about'
    | '/onboarding/audience'
    | '/onboarding/finish'
    | '/onboarding/sources'
    | '/app/'
    | '/onboarding/'
    | '/api/auth/$'
    | '/app/drafts/$draftId'
    | '/app/drafts/new'
    | '/app/icps/$icpId'
    | '/app/outcomes/$outcomeId'
    | '/app/settings/integrations'
    | '/app/settings/members'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/workspace'
    | '/app/signals/$signalId'
    | '/app/watchlists/$watchlistId'
    | '/app/drafts/'
    | '/app/icps/'
    | '/app/outcomes/'
    | '/app/watchlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/register'
    | '/app/settings'
    | '/app/analytics'
    | '/app/feedback'
    | '/app/inbox'
    | '/app/sources'
    | '/app/summaries'
    | '/app/support'
    | '/onboarding/about'
    | '/onboarding/audience'
    | '/onboarding/finish'
    | '/onboarding/sources'
    | '/app'
    | '/onboarding'
    | '/api/auth/$'
    | '/app/drafts/$draftId'
    | '/app/drafts/new'
    | '/app/icps/$icpId'
    | '/app/outcomes/$outcomeId'
    | '/app/settings/integrations'
    | '/app/settings/members'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/workspace'
    | '/app/signals/$signalId'
    | '/app/watchlists/$watchlistId'
    | '/app/drafts'
    | '/app/icps'
    | '/app/outcomes'
    | '/app/watchlists'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/login'
    | '/mcp'
    | '/register'
    | '/app/settings'
    | '/app/analytics'
    | '/app/feedback'
    | '/app/inbox'
    | '/app/sources'
    | '/app/summaries'
    | '/app/support'
    | '/onboarding/about'
    | '/onboarding/audience'
    | '/onboarding/finish'
    | '/onboarding/sources'
    | '/app/'
    | '/onboarding/'
    | '/api/auth/$'
    | '/app/drafts/$draftId'
    | '/app/drafts/new'
    | '/app/icps/$icpId'
    | '/app/outcomes/$outcomeId'
    | '/app/settings/integrations'
    | '/app/settings/members'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/workspace'
    | '/app/signals/$signalId'
    | '/app/watchlists/$watchlistId'
    | '/app/drafts/'
    | '/app/icps/'
    | '/app/outcomes/'
    | '/app/watchlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/onboarding/sources': {
      id: '/onboarding/sources'
      path: '/sources'
      fullPath: '/onboarding/sources'
      preLoaderRoute: typeof OnboardingSourcesRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/finish': {
      id: '/onboarding/finish'
      path: '/finish'
      fullPath: '/onboarding/finish'
      preLoaderRoute: typeof OnboardingFinishRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/audience': {
      id: '/onboarding/audience'
      path: '/audience'
      fullPath: '/onboarding/audience'
      preLoaderRoute: typeof OnboardingAudienceRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/about': {
      id: '/onboarding/about'
      path: '/about'
      fullPath: '/onboarding/about'
      preLoaderRoute: typeof OnboardingAboutRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/summaries': {
      id: '/app/summaries'
      path: '/summaries'
      fullPath: '/app/summaries'
      preLoaderRoute: typeof AppSummariesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sources': {
      id: '/app/sources'
      path: '/sources'
      fullPath: '/app/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/watchlists/': {
      id: '/app/watchlists/'
      path: '/watchlists'
      fullPath: '/app/watchlists/'
      preLoaderRoute: typeof AppWatchlistsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/outcomes/': {
      id: '/app/outcomes/'
      path: '/outcomes'
      fullPath: '/app/outcomes/'
      preLoaderRoute: typeof AppOutcomesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/icps/': {
      id: '/app/icps/'
      path: '/icps'
      fullPath: '/app/icps/'
      preLoaderRoute: typeof AppIcpsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/drafts/': {
      id: '/app/drafts/'
      path: '/drafts'
      fullPath: '/app/drafts/'
      preLoaderRoute: typeof AppDraftsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/watchlists/$watchlistId': {
      id: '/app/watchlists/$watchlistId'
      path: '/watchlists/$watchlistId'
      fullPath: '/app/watchlists/$watchlistId'
      preLoaderRoute: typeof AppWatchlistsWatchlistIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/signals/$signalId': {
      id: '/app/signals/$signalId'
      path: '/signals/$signalId'
      fullPath: '/app/signals/$signalId'
      preLoaderRoute: typeof AppSignalsSignalIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/workspace': {
      id: '/app/settings/workspace'
      path: '/workspace'
      fullPath: '/app/settings/workspace'
      preLoaderRoute: typeof AppSettingsWorkspaceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/members': {
      id: '/app/settings/members'
      path: '/members'
      fullPath: '/app/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/integrations': {
      id: '/app/settings/integrations'
      path: '/integrations'
      fullPath: '/app/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/outcomes/$outcomeId': {
      id: '/app/outcomes/$outcomeId'
      path: '/outcomes/$outcomeId'
      fullPath: '/app/outcomes/$outcomeId'
      preLoaderRoute: typeof AppOutcomesOutcomeIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/icps/$icpId': {
      id: '/app/icps/$icpId'
      path: '/icps/$icpId'
      fullPath: '/app/icps/$icpId'
      preLoaderRoute: typeof AppIcpsIcpIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/drafts/new': {
      id: '/app/drafts/new'
      path: '/drafts/new'
      fullPath: '/app/drafts/new'
      preLoaderRoute: typeof AppDraftsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/drafts/$draftId': {
      id: '/app/drafts/$draftId'
      path: '/drafts/$draftId'
      fullPath: '/app/drafts/$draftId'
      preLoaderRoute: typeof AppDraftsDraftIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsWorkspaceRoute: typeof AppSettingsWorkspaceRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsWorkspaceRoute: AppSettingsWorkspaceRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppInboxRoute: typeof AppInboxRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppSummariesRoute: typeof AppSummariesRoute
  AppSupportRoute: typeof AppSupportRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDraftsDraftIdRoute: typeof AppDraftsDraftIdRoute
  AppDraftsNewRoute: typeof AppDraftsNewRoute
  AppIcpsIcpIdRoute: typeof AppIcpsIcpIdRoute
  AppOutcomesOutcomeIdRoute: typeof AppOutcomesOutcomeIdRoute
  AppSignalsSignalIdRoute: typeof AppSignalsSignalIdRoute
  AppWatchlistsWatchlistIdRoute: typeof AppWatchlistsWatchlistIdRoute
  AppDraftsIndexRoute: typeof AppDraftsIndexRoute
  AppIcpsIndexRoute: typeof AppIcpsIndexRoute
  AppOutcomesIndexRoute: typeof AppOutcomesIndexRoute
  AppWatchlistsIndexRoute: typeof AppWatchlistsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppInboxRoute: AppInboxRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppSummariesRoute: AppSummariesRoute,
  AppSupportRoute: AppSupportRoute,
  AppIndexRoute: AppIndexRoute,
  AppDraftsDraftIdRoute: AppDraftsDraftIdRoute,
  AppDraftsNewRoute: AppDraftsNewRoute,
  AppIcpsIcpIdRoute: AppIcpsIcpIdRoute,
  AppOutcomesOutcomeIdRoute: AppOutcomesOutcomeIdRoute,
  AppSignalsSignalIdRoute: AppSignalsSignalIdRoute,
  AppWatchlistsWatchlistIdRoute: AppWatchlistsWatchlistIdRoute,
  AppDraftsIndexRoute: AppDraftsIndexRoute,
  AppIcpsIndexRoute: AppIcpsIndexRoute,
  AppOutcomesIndexRoute: AppOutcomesIndexRoute,
  AppWatchlistsIndexRoute: AppWatchlistsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingAboutRoute: typeof OnboardingAboutRoute
  OnboardingAudienceRoute: typeof OnboardingAudienceRoute
  OnboardingFinishRoute: typeof OnboardingFinishRoute
  OnboardingSourcesRoute: typeof OnboardingSourcesRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingAboutRoute: OnboardingAboutRoute,
  OnboardingAudienceRoute: OnboardingAudienceRoute,
  OnboardingFinishRoute: OnboardingFinishRoute,
  OnboardingSourcesRoute: OnboardingSourcesRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
